select *
FROM CARS;

SELECT BRAND,MODEL,PRICE 
FROM CARS
WHERE PRICE < 100000;

SELECT BRAND, PRICE, MODEL
FROM CARS
ORDER  BY PRICE DESC;

SELECT 
S.SALE_ID,
CAR.BRAND,
CAR.MODEL,
S.QUANTITY
FROM SALES S
INNER JOIN CARS CAR ON  S.CAR_ID = CAR.CAR_ID;

SELECT 
FIRST_NAME,
LAST_NAME,
CITY
FROM CUSTOMERS
WHERE CITY = 'London';

SELECT CATEGORY, COUNT(*) AS TOTAL_CARS
FROM CARS
GROUP BY CATEGORY;

SELECT CATEGORY, MAX(PRICE) AS MOST_EXPENSIVE
FROM CARS
GROUP BY CATEGORY;

SELECT BRAND, MODEL, PRICE
FROM CARS
WHERE PRICE > (SELECT AVG(PRICE) FROM CARS);

SELECT 
   BRAND,
   MODEL,
   PRICE,
   CASE
      WHEN PRICE >= 500000 THEN 'Hyper Luxury'
      WHEN PRICE >= 150000 THEN 'Premium Sport'
      ELSE 'Standard Segment'
   END AS CAR_TIER
FROM CARS
ORDER BY PRICE DESC;

SELECT
CATEGORY,
MAX(PRICE) AS MOST_EXPENSIVE 
FROM CARS
GROUP BY CATEGORY
HAVING MAX (PRICE) >= 200000;